"""init domain schema

와이어프레임(Manyfast/Figma) 대조 후 2026-09-30 합의 반영:
- 구역(parking_zones) → 칸(parking_slots, 구역 안 번호 + 2.5D 로컬 좌표 + 앞 칸)
- 시간제 공유 차고지(garages), 이메일 가입 + 초대코드(buildings.invite_code)
- 이동 요청(move_requests), 알림 원인 FK
- 제약: 활성 배치 칸/차 유일, 공유 수락 시간 겹침 금지(btree_gist) 등 (docs/db-design-issues.md)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 16:47:51.280496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # share_requests 의 EXCLUDE 제약(slot_id = , tsrange &&)에 필요
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('detail_address', sa.String(length=255), nullable=True),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    # idx_buildings_location(gist) 는 GeoAlchemy2 가 create_table 시 자동 생성한다
    op.create_table('garages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available_start', sa.Time(), nullable=False),
    sa.Column('available_end', sa.Time(), nullable=False),
    sa.Column('available_weekdays', sa.ARRAY(sa.Integer()), server_default=sa.text("'{0,1,2,3,4,5,6}'"), nullable=False),
    sa.Column('hourly_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_hours', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_start < available_end', name='ck_garage_available_time'),
    sa.CheckConstraint('available_weekdays <@ ARRAY[0,1,2,3,4,5,6]', name='ck_garage_weekdays'),
    sa.CheckConstraint('hourly_fee >= 0', name='ck_garage_fee'),
    sa.CheckConstraint('max_hours IS NULL OR max_hours > 0', name='ck_garage_max_hours'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('zone_type', sa.Enum('PILOTI_IN', 'PILOTI_OUT', 'ALLEY', name='zone_type'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_zone_name_per_building')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('unit_no', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('RESIDENT', 'MANAGER', name='resident_role'), server_default='RESIDENT', nullable=False),
    sa.Column('manner_temperature', sa.Float(), server_default='36.5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('manner_temperature BETWEEN 0 AND 99.9', name='ck_resident_manner_temperature'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('front_slot_id', sa.Integer(), nullable=True),
    sa.Column('render_x0', sa.Float(), nullable=True),
    sa.Column('render_y0', sa.Float(), nullable=True),
    sa.Column('render_x1', sa.Float(), nullable=True),
    sa.Column('render_y1', sa.Float(), nullable=True),
    sa.Column('is_shareable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('front_slot_id IS NULL OR front_slot_id <> id', name='ck_slot_front_not_self'),
    sa.CheckConstraint('number > 0', name='ck_slot_number_positive'),
    sa.ForeignKeyConstraint(['front_slot_id'], ['parking_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garage_id'], ['garages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'number', name='uq_slot_number_per_zone')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_no', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_no')
    )
    op.create_index('uq_primary_vehicle_per_owner', 'vehicles', ['owner_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('departure_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('repeat_weekdays', sa.ARRAY(sa.Integer()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_ai_estimated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('repeat_weekdays <@ ARRAY[0,1,2,3,4,5,6]', name='ck_departure_weekdays'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('blocked_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('needed_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MOVED', 'DECLINED', name='move_request_status'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('blocked_vehicle_id IS NULL OR blocked_vehicle_id <> target_vehicle_id', name='ck_move_request_distinct_vehicles'),
    sa.ForeignKeyConstraint(['blocked_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_pending_move_request_target', 'move_requests', ['target_vehicle_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('parking_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_permanent', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('is_active = (released_at IS NULL)', name='ck_assignment_active_released'),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_assignment_slot', 'parking_assignments', ['slot_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('uq_active_assignment_vehicle', 'parking_assignments', ['vehicle_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('share_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='share_request_status'), server_default='PENDING', nullable=False),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    postgresql.ExcludeConstraint((sa.column('slot_id'), '='), (sa.text('tsrange(request_date + start_time, request_date + end_time)'), '&&'), where=sa.text("status = 'ACCEPTED'"), using='gist', name='ex_share_accepted_overlap'),
    sa.CheckConstraint('start_time < end_time', name='ck_share_time_order'),
    sa.ForeignKeyConstraint(['requester_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPARTURE_REMINDER', 'SHARE_REQUEST', 'SHARE_RESPONSE', 'MOVE_REQUEST', 'MOVE_RESPONSE', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('share_request_id', sa.Integer(), nullable=True),
    sa.Column('move_request_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['move_request_id'], ['move_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_request_id'], ['share_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('share_requests')
    op.drop_index('uq_active_assignment_vehicle', table_name='parking_assignments', postgresql_where=sa.text('is_active'))
    op.drop_index('uq_active_assignment_slot', table_name='parking_assignments', postgresql_where=sa.text('is_active'))
    op.drop_table('parking_assignments')
    op.drop_index('uq_pending_move_request_target', table_name='move_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('move_requests')
    op.drop_table('departure_schedules')
    op.drop_index('uq_primary_vehicle_per_owner', table_name='vehicles', postgresql_where=sa.text('is_primary'))
    op.drop_table('vehicles')
    op.drop_table('parking_slots')
    op.drop_table('residents')
    op.drop_table('parking_zones')
    op.drop_table('garages')
    op.drop_table('buildings')
    # ### end Alembic commands ###

    # drop_table 은 PostgreSQL enum 타입을 지우지 않는다
    for enum_name in ("notification_type", "share_request_status", "move_request_status", "resident_role", "zone_type"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name};")
    op.execute("DROP EXTENSION IF EXISTS btree_gist;")
