"""명세(docs/openapi-mock.yaml)의 `components.schemas.ErrorCode` enum 17개.

에러 응답의 `error.code` 에는 이 값만 쓴다. 명세에 코드를 추가하면 여기에도 추가한다.
"""

import enum


class ErrorCode(enum.StrEnum):
    # 400
    INVALID_INPUT = "INVALID_INPUT"
    # 401
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    # 403
    NOT_BUILDING_MEMBER = "NOT_BUILDING_MEMBER"
    NOT_BUILDING_ADMIN = "NOT_BUILDING_ADMIN"
    # 404
    NOT_FOUND = "NOT_FOUND"
    INVALID_INVITE_CODE = "INVALID_INVITE_CODE"
    # 409
    EMAIL_EXISTS = "EMAIL_EXISTS"
    SLOT_OCCUPIED = "SLOT_OCCUPIED"
    SLOT_UNAVAILABLE = "SLOT_UNAVAILABLE"
    VEHICLE_ALREADY_PARKED = "VEHICLE_ALREADY_PARKED"
    GARAGE_TIME_CONFLICT = "GARAGE_TIME_CONFLICT"
    # 409 (명세 열린 질문 11: v0.2 미정의 → 제안으로 추가)
    PLATE_EXISTS = "PLATE_EXISTS"
    ALREADY_DECIDED = "ALREADY_DECIDED"
    MOVE_REQUEST_ALREADY_PENDING = "MOVE_REQUEST_ALREADY_PENDING"
    ALREADY_IN_BUILDING = "ALREADY_IN_BUILDING"
    INSUFFICIENT_TOKENS = "INSUFFICIENT_TOKENS"
